publications/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home_page, name='home_page'),
    path('articles/', include('publicationsapp.urls'), name='articles'),
    path('authors/', include('publicationsapp.author_urls'), name='authors'),
]

publicationsapp/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView
from .models import Article
from . import views

urlpatterns = [
    path('new/', views.new, name='new_article'),
    path('', ListView.as_view(queryset=Article.objects.all().order_by("-date")[:10]
    , template_name="articles/posts.html"), name='all_articles'),
    path('<slug:pk>/', views.show, name='show_article'),
    path('<slug:pk>/update', views.update, name='update'),
    path('json_update', views.json_update, name='json_update'),
    path('<slug:pk>/delete', views.ArticleDelete.as_view(), name="delete_article"),
    #path('<slug:pk>/', DetailView.as_view(model=Article, template_name="articles/post.html")),
]

publicationsapp/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from datetime import datetime

class Author(models.Model):
    firstName = models.CharField(max_length = 50)
    secondName = models.CharField(max_length = 50)
    patronymic = models.CharField(max_length = 50)

    firstName_en = models.CharField(max_length = 50)
    secondName_en = models.CharField(max_length = 50)
    patronymic_en = models.CharField(max_length = 50)

    def __str__(self):
        return u'%s %s. %s.' % (self.secondName, self.firstName[0], self.patronymic[0])

class Article(models.Model):
    title = models.CharField(max_length = 120)
    metainfo = models.TextField()
    #metainfo = JSONField()
    date = models.DateTimeField(default = datetime.now(), blank=True, null=True)
    authors = models.ManyToManyField(Author, blank=True)

    def __str__(self):
        return self.title

publicationsapp/forms.py
from django import forms
#from django.forms.extras.widgets import SelectDateWidget
from .models import Article, Author

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ["date", "authors"]

class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        exclude = [""]

class ArticleUpdateForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ["date"]

publications/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'home_page.html', locals())

publicationsapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import DeleteView
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.urls import reverse_lazy
from .models import Article, Author
from .forms import ArticleForm, AuthorForm, ArticleUpdateForm
import json

def new(request):
    if request.method == "POST":
        data = {
            'title': request.POST["title"],
            'metainfo': {
                'body': request.POST["metainfo"],
            },
        }
        form = ArticleForm(data)
        if form.is_valid():
            new_form = form.save()
    else:
        form = ArticleForm()
    return render(request, 'articles/new.html', locals())

class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('all_articles')

    template_name = 'articles/delete.html'

def json_update(request):
    article_id = request.GET.get("article_id")
    article = get_object_or_404(Article, pk=article_id)
    data = serializers.serialize('json', [ article, ])
    return HttpResponse(data)
    # return JsonResponse(data)

def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    authors = article.authors.all()
    if request.method == 'POST':
        form = ArticleUpdateForm(request.POST)
        if form.is_valid():
            data = {'body': form.cleaned_data['metainfo'],}
            for k, v in dict(request.POST).items():
                v=v[0]
                if k[:5] == 'param' and k.find('name') > 0:
                    data[v] = request.POST[k[:-4]]
            # if ('param3' in request.POST):
            #     data = {
            #         request.POST['param3name']: request.POST['param3'],
            #         "body": form.cleaned_data['metainfo'],
            #     }

            article.title = form.cleaned_data['title']
            article.metainfo = data
            article.authors.set(form.cleaned_data['authors'])
            article.save()
        return render(request, 'articles/new.html', locals())
    else:
        metainfo = article.metainfo.replace('\'', '\"')
        metainfo_js = json.loads(metainfo)
        form = ArticleUpdateForm(initial={
            'title': article,
            'metainfo' : metainfo_js['body'],
            'date' : article.date,
            #'authors' : article.authors
            })
        return render(request, 'articles/new.html', locals())

def show(request, pk):
    article = get_object_or_404(Article, pk=pk)
    metainfo = article.metainfo
    metainfo = json.loads(metainfo.replace('\'', '\"'))
    authors = article.authors.all()
    return render(request, 'articles/post.html', locals())

publicationsapp/templates/articles/delete.html
<div class="container">
  Hey, are you sure you want to delete {{ object.title }}?
  <form method="post">
    <div class="form-group">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Yeap, I'm sure.</button>
    </div>
  </form>
</div>

publicationsapp/templates/articles/new.html
{% extends "wrapper.html" %}

{% block content %}
<div class="container">
  <form action="" method="post">{% csrf_token %}
    <div class="form-group">
      <label>Заголовок</label>
      <input type="text" name="title" class="form-control" id="id_title"
       {% if form.title.value != None %}value="{{ form.title.value|stringformat:'s' }}"{% endif %}>
    </div>
    <div class="form-group">
      <label>Текст</label>
      <textarea type="text" name="metainfo" class="form-control" id="id_metainfo" rows="5">{% if form.metainfo.value != None %}{{ form.metainfo.value|stringformat:'s' }}{% endif %}</textarea>
    </div>
    <div class="form-group">
      {{form.authors}}
    </div>
    {% if article %}
    <div class="form-group">
      <button type="button" class="btn btn-light json" style="margin-top:15px">Добавить поле</button>
    </div>
    {% endif %}
    <div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
  </form>
</div>
<script>

  $(document).ready(function(){
    $('.json').on('click', function(){
      new_field = $('.json')
      data = {
        article_id: '{{article.id}}'
      }

      $.ajax({
        type: "GET",
        url: "{% url 'json_update' %}",
        data: data,
        dataType: 'json',
        success: function(data){
          console.log(data)
          id = ($('.new-param').length+1)
          new_field.before("<div class='form-inline'><input type='text' name='param"+id+"name' class='form-control' id='id_param"+id+"name' value='Новое поле'><input type='text' name='param"+id+"' class='form-control new-param' id='id_param"+id+"' value="+($('.new-param').length+1)+"></div><br/>")
        }
      })
    })
  })

</script>
{% endblock %}

publicationsapp/templates/articles/post.html
{% extends "wrapper.html" %}
{% load staticfiles %}

{% block content %}

  <!-- Page Content -->
  <div class="container">
      <div class="row">
          <!-- Blog Post Content Column -->
          <div class="col-lg-8">
            <!-- Blog Post -->
              <!-- Title -->
              <h1>{{article.title}}</h1>

              <!-- Author -->
              {% for author in article.authors.all %}
                {% if author == article.authors.first %}
                  by <a href="/authors/{{author.id}}">{{author}}</a>
                {% else %}
                  , <a href="/authors/{{author.id}}">{{author}}</a>
                {% endif %}
              {% empty %}
                author not specified
              {% endfor %}

              <p><a href="/articles/{{article.id}}/update">Редактировать<a></p>
              <p><a href="{% url 'delete_article' pk=article.id %}">Удалить<a></p>

              <hr>
              <!-- Date/Time -->
              <p><span class="glyphicon glyphicon-time"></span> Posted on {{article.date|date:"M d, Y \a\t H:i"}}</p>
              <hr>
              <!-- Preview Image -->
              <img class="img-fluid" src="http://placehold.it/900x300" alt="">
              <hr>
              <!-- Post Content -->
              <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
              <p>{{metainfo.body|safe|linebreaks}}</p>
              <hr>
              {% for k, v in metainfo.items %}
                {% if k != 'body' %}
                  <p>{{k}}: {{v}}</p>
                {% endif %}
              {% empty %}

              {% endfor %}
              <hr>

              <!-- Blog Comments -->

              <!-- Comments Form -->
              <div class="card card-body bg-light">
                  <h4 class="card-title">Leave a Comment:</h4>
                  <form role="form">
                      <div class="form-group">
                          <textarea class="form-control" rows="3"></textarea>
                      </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
              </div>

              <hr>

              <!-- Posted Comments -->
              <ul class="list-unstyled">

                <!-- Comment -->
                <li class="media">
                    <img class="mr-3" src="http://placehold.it/64x64" alt="">
                    <div class="media-body">
                        <h4 class="mt-0">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </li>

                <!-- Comment -->
                <li class="media">
                  <img class="mr-3" src="http://placehold.it/64x64" alt="">
                  <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media mt-3">
                            <img class="mr-3" src="http://placehold.it/64x64" alt="">
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </li>
              </ul>

          </div>

          <!-- Sidebar Widgets Column -->
          <div class="col-md-4">

            {% include "widgets_column.html" %}

          </div>

      </div>
      <!-- /.row -->

      <hr>

      <!-- Footer -->
      <footer>
          <div class="row">
              <div class="col-lg-12">
                  <p>Copyright &copy; Your Website 2014</p>
              </div>
          </div>
          <!-- /.row -->
      </footer>

  </div>
  <!-- /.container -->
  <!-- jQuery -->
  <script src="js/jquery.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

publicationsapp/templates/articles/posts.html
{% extends "wrapper.html" %}

{% block content %}

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Page Heading
          <small>Secondary Text</small>
        </h1>

        {% for article in object_list %}

          <!-- Blog Post -->
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title">{{article.title}}</h2>
              <p class="card-text">{{article.metainfo}}</p>
              <a href="/articles/{{article.id}}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on {{article.date|date:"M d, Y"}}
              {% for author in article.authors.all %}
                {% if author == article.authors.first %}
                  by <a href="/authors/{{author.id}}">{{author}}</a>
                {% else %}
                  , <a href="/authors/{{author.id}}">{{author}}</a>
                {% endif %}
              {% empty %}
                , author not specified
              {% endfor %}
            </div>
          </div>
        {% endfor %}


        <!-- Blog Post -->
        <div class="card mb-4">
          <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
          <div class="card-body">
            <h2 class="card-title">Post Title</h2>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
            <a href="#" class="btn btn-primary">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Posted on January 1, 2017 by
            <a href="#">Start Bootstrap</a>
          </div>
        </div>

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item disabled">
            <a class="page-link" href="#">&larr; Новые</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">Старые &rarr;</a>
          </li>
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        {% include "widgets_column.html" %}

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

{% endblock %}

publicationsapp/templates/authors/author.html
{% extends "wrapper.html" %}

{% block content %}
  <h2 class="text-info">{{author.name}}</h2>
  <h6 class="text-info">Публикации:</h6>

  {% for article in articles %}
    <a href="/articles/{{article.id}}"><p>{{article}}</p></a>
  {% empty %}
    <p>Публикации не указаны</p>
  {% endfor %}

{% endblock %}

publicationsapp/templates/authors/authors.html
{% extends "wrapper.html" %}

{% block content %}
  {% for author in object_list %}
    <a href="/authors/{{author.id}}"<h3><p>{{author}}</p></h3></a>
  {% endfor %}
{% endblock %}

publicationsapp/templates/authors/new.html
{% extends "wrapper.html" %}

{% block content %}
  <form action="" method="post">{% csrf_token %}
    <div class="form-group">
      <label>Имя</label>
      <input type="text" name="name" class="form-control" id="id_name"
       {% if form.name.value != None %}value="{{ form.name.value|stringformat:'s' }}"{% endif %}>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
  </form>
{% endblock %}

publicationsapp/templates/footer.html
{% block content %}

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
  </footer>

{% endblock %}

publicationsapp/templates/home_page.html
{% extends "wrapper.html" %}

{% block content %}
  <h1>Hello</h1>
{% endblock %}

publicationsapp/templates/navbar.html
{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Publications</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% url 'all_articles' as the_url %}
        <li class="nav-item {% if request.path == the_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'all_articles' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == '/authors/' %}active{% endif %}">
          <a class="nav-link" href="/authors">Авторы</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Добавить
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/authors/new">Автора</a>
            <a class="dropdown-item" href="/articles/new">Публикацию</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% endblock %}

publicationsapp/templates/widgets_column.html
{% block content %}

  <!-- Search Widget -->
  <div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="button">Go!</button>
        </span>
      </div>
    </div>
  </div>

  <!-- Categories Widget -->
  <div class="card my-4">
    <h5 class="card-header">Categories</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#">Web Design</a>
            </li>
            <li>
              <a href="#">HTML</a>
            </li>
            <li>
              <a href="#">Freebies</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#">JavaScript</a>
            </li>
            <li>
              <a href="#">CSS</a>
            </li>
            <li>
              <a href="#">Tutorials</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Side Widget -->
  <div class="card my-4">
    <h5 class="card-header">Side Widget</h5>
    <div class="card-body">
      You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
    </div>
  </div>

{% endblock %}

publicationsapp/templates/wrapper.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name = "viewport" content = "width=decive-width, initial-scale=1.0">
  <meta http-equiv="default-style" content="ie=edge">
  <title>Заголовок</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
  <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<body>
  {% include "navbar.html" %}

  {% block content %}
  {% endblock %}


</body>
</html>